### ISSUE TITLE
[Bug] Orderable on columns of type custom_column has not been disabled

### ISSUE THREAD

**Issue by tringuyenduc2903** [Laravel-Backpack/activity-log#39] opened 2024-04-07 15:54 UTC
# Bug report

### What I did

Test the sort operation on the entire column

### What I expected to happen

Sort successfully

### What happened

![image](https://github.com/Laravel-Backpack/activity-log/assets/101564593/57fcd0e5-32ed-4686-8c7b-4d2ba2918351)

**Causer**, **Subject** in **Activity Logs**
![image](https://github.com/Laravel-Backpack/activity-log/assets/101564593/da8eca5a-396e-4f3d-913d-df507a98d847)

### What I've already tried to fix it

```php
 // Add attribute to column
 'orderable' => false
```
This issue is similar to Add-ons **Backpack\PermissionManager** at https://github.com/Laravel-Backpack/PermissionManager/issues/357

### Context to replicate the bug - Backpack, Laravel, PHP, DB version

When I run ```php artisan backpack:version``` the output is:

```
### PHP VERSION:
8.3.4

### PHP EXTENSIONS:
Core, date, libxml, openssl, pcre, zlib, filter, hash, json, pcntl, random, Reflection, SPL, session, standard, sodium, mysqlnd, PDO, xml, bcmath, calendar, ctype, curl, dom, mbstring, FFI, fileinfo, ftp, gd, gettext, iconv, igbinary, imagick, imap, intl, ldap, exif, msgpack, mysqli, pcov, pdo_mysql, pdo_pgsql, pdo_sqlite, pgsql, Phar, posix, readline, redis, shmop, SimpleXML, soap, sockets, sqlite3, sysvmsg, sysvsem, sysvshm, tokenizer, xmlreader, xmlwriter, xsl, zip, memcached, swoole, Zend OPcache, xdebug

### LARAVEL VERSION:
11.2.0.0

### BACKPACK PACKAGE VERSIONS:
backpack/activity-log: 2.0.2
backpack/backupmanager: v5.0.2
backpack/basset: 1.3.0
backpack/crud: 6.7.5
backpack/filemanager: 3.0.7
backpack/generators: v4.0.5
backpack/language-switcher: 2.0.0
backpack/logmanager: v5.0.1
backpack/medialibrary-uploaders: 1.2.0
backpack/permissionmanager: 7.2.0
backpack/pro: 2.1.12
backpack/revise-operation: 2.0.0
backpack/theme-tabler: 1.2.8
```

**Comment by promatik** [comment] 2024-04-07 18:12
Hi @tringuyenduc2903!
Again I can't reproduce your issue... can you give us some hint?

It's working on our demo; https://demo.backpackforlaravel.com/admin/activity-log
I also tested it locally, but everything seems to work as expected.

I'll close this one, let's move conversation to https://github.com/Laravel-Backpack/PermissionManager/issues/357 since it's apparently the same problem 👌

**Closed by promatik** 2024-04-07 18:12 UTC
