### ISSUE TITLE
[Bug] Error when using Subject filter

### ISSUE THREAD

**Issue by tabacitu** [Laravel-Backpack/activity-log#4] opened 2022-12-06 08:49 UTC
# Bug report

![CleanShot 2022-12-06 at 10 47 21](https://user-images.githubusercontent.com/1032474/205864050-fac71795-ed15-4f23-a8c8-79cce8f6f88c.gif)

### What I did

- Made some changes to some Book entries.
- Went to activity log and wanted to only filter those with a certain "subject"

### What I expected to happen

A filtered list of those that include the keyword.

### What happened

Big ass Livewire error.

### What I've already tried to fix it

![george-costanza-seinfeld-gif](https://user-images.githubusercontent.com/1032474/205864003-6c75f28d-d287-4d25-8037-c27eae03ad31.gif)

**Comment by promatik** [comment] 2023-04-14 04:29
I should have though about this one 👌

I think this happens because I'm guessing the name of the entity, using `$model->identifiableAttribute()`. And probably, the attribute is not being guessed, and is falling back to `name` that doesn't exists ...

@tabacitu, can you just confirm what's that entity identifiable attribute? and maybe confirm that `$model->identifiableAttribute()` doesn't work?

**Comment by pxpm** [comment] 2023-04-14 08:42
> I should have though about this one 👌
> 
> I think this happens because I'm guessing the name of the entity, using `$model->identifiableAttribute()`. And probably, the attribute is not being guessed, and is falling back to `name` that doesn't exists ...
> 
> @tabacitu, can you just confirm what's that entity identifiable attribute? and maybe confirm that `$model->identifiableAttribute()` doesn't work?

AFAIK, `identifiableAttribute()` will never return an attribute that does not exist. It will bail out with "the first found column" (ususally id if we can't find any other).

**Comment by promatik** [comment] 2023-08-21 00:53
I was able to reproduce this one 🙌
And it's finally fixed with https://github.com/Laravel-Backpack/activity-log/pull/8 👌

**Closed by promatik** 2023-08-21 00:53 UTC
